ROUTE = [
    "gerais",
    "polivalente",
    "auditorio",
    "dec",
    "altice",
    "dem",
    "dee",
    "gab_electro",
    "deem",
    "lab_mecanica",
    "lab_civil",
    "horta",
    "carregador",
    "deis",
    "cantina",
    "clinica",
    "reprografia",
    "aeisec",
    "festas",
    "deqb",
    "bar_loja",
]

DEFAULT_MESSAGES = [
    "Siga-me, eu não estou perdido",
    "Eu a trabalhar e tu a dormir! Mexe-te",
    "O próximo ponto não vem ter contigo",
    "Estás a andar devagar de propósito? Anda lá",
    "É por aqui. Juro, Joca",
    "Se te perderes, a culpa não é minha",
    "Bonito desvio. Agora segue mas é a bússola",
    "Não inventes. É por aqui",
    "A seta não é para decoração. É para seguir",
    "Estás quase... a estar quase",
    "Não compliques. É em frente",
    "Tens uma seta. O ISEC não é enorme. Qual a desculpa?",
    "A sério que vais por aí? lol",
    "Está a demorar mais do que devia",
    "Se isto fosse turismo havia gelados. Mexe-te",
    "Se isto fosse fácil já lá estavas",
    "Isto não é um museu. Toca a andar",
    "A seta está a fazer o seu trabalho. E tu?",
    "Excelente ritmo... Se o objetivo fosse não chegar",
    "Ritmo impressionante. Lento, mas impressionante",
    "Se o objetivo for falhar, estás a ir muito bem ",
    "Se te perderes, pelo menos foi com estilo",
    "A seta está certa. Tu é que não",
    "Não sei o que estás a fazer, mas não é isto",
    "Continua assim e chegas... a outro sítio",
    "Menos instinto, mais seta",
]

POI_DICT = {
    "start": "Ponto de Partida",
    "gerais": "Gerais / Departamento de Física e Matemática",
    "polivalente": "Edifício Polivalente",
    "auditorio": "Auditório",
    "dec": "Departamento de Engenharia Civil",
    "altice": "Laboratório da Altice",
    "dem": "Departamento de Engenharia Mecânica",
    "dee": "Departamento de Engenharia Eletrotécnica",
    "gab_electro": "Gabinete Técnico de Eletrotecnia",
    "deem": "Departamento de Engenharia Eletromecânica",
    "lab_mecanica": "Laboratórios de Engenharia Mecânica",
    "lab_civil": "Laboratórios de Engenharia Civil",
    "horta": "EcoCampus / Horta Urbana",
    "carregador": "Carregador de Veículos Elétricos",
    "deis": "Departamento de Engenharia Informática e de Sistemas",
    "cantina": "Cantina",
    "clinica": "Clínica IPC",
    "reprografia": "Reprografia",
    "aeisec": "Associação de Estudantes do ISEC",
    "festas": "Local de Festas",
    "deqb": "Departamento de Engenharia Química e Biológica",
    "bar_loja": "Bar e Loja",
}
